name: Add to Contributors
on:
  push:
    branches:
    - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.TEST_TOKEN }}
          pr-message: 'Adding this ${{ github.event.pull_request.user.login }} to Contributors...'
          issue-message: 'Adding this ${{ github.event.issue.user.login }} to Contributors...'