name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '  Hello there!👋 Welcome to the project!🚀⚡
  Thank you and congrats🎉 for opening your very first issue in this project.
  Please make sure not to start working on the issue, unless you get assigned to it.😄'
        pr-message: 'Congratulations!! for making your first PR, our mentors will review it soon. 🙌🏻'